### ISSUE TITLE
Error while testing with graphiql

### ISSUE THREAD

**Issue by tonihaupt** [whuysmans/vuewp-graphql#1]
Heyho and thanks for the nice work. When i activate this plugin i get invalid json error inside graphiql and loading the /graphql endpoint. Using the original wp-graphql plugin works as expected.
Are there some know issues or how to solve this bug (when it is a bug :) )

**Comment by whuysmans** [comment]
Hi,

did you get an 'invalid token <' error? That is probably because the result returns html instead of json. Can you try to update the permalink structure in your WP install to 'post name'?

**Comment by tonihaupt** [comment]
Thanks for your fast reply. I get the following error:
SyntaxError: Unexpected token < in JSON at position 0

<img width="1173" alt="bildschirmfoto 2017-04-20 um 10 11 05" src="https://cloud.githubusercontent.com/assets/26216106/25220333/bce52280-25b1-11e7-9ab4-e4a4a50c1cc9.png">

**Comment by whuysmans** [comment]
Did you update the permalinks and still get this error? In that case, can you try to change the Access-Control-Allow-Origin header in the index.php of the plugin to: 
header('Access-Control-Allow-Origin: *');

**Comment by tonihaupt** [comment]
Okay. First thanks for your help very quick :)
I changed permalinks to %postname and the header to * here is a screen from errors happening inside grapgiql.

<img width="1168" alt="bildschirmfoto 2017-04-20 um 10 37 29" src="https://cloud.githubusercontent.com/assets/26216106/25221457/780a61bc-25b5-11e7-9cbb-1f45df33d99e.png">

**Comment by whuysmans** [comment]
sorry if I wasn't clear, I meant change the permalinks to the option 'post name', like: https://example.com/sample-post

**Comment by tonihaupt** [comment]
Hehe no problem have done that. Just written the placeholder used in wp /%postname%/ wich in results in http://mydevdomain.dev/sample-post

<img width="837" alt="bildschirmfoto 2017-04-20 um 10 47 02" src="https://cloud.githubusercontent.com/assets/26216106/25221826/ce3093da-25b6-11e7-9e9b-d3319dd22444.png">

**Comment by whuysmans** [comment]
Well, the error means that you are still receiving html instead of json... Right now, I don't see any reason why this is happening. I will try to reproduce it later today.

**Comment by tonihaupt** [comment]
MAybe my dev machine? Running it with laravel valet (nginx) but should have nothing to do with this error. When i activate the original wp-graphql plugin, everything works as expected.

**Comment by whuysmans** [comment]
I just changed some WP-related stuff in the original plugin, nothing graphql-related, except for the headers in the index.php, and the namespacing and file structure of the dependencies. Maybe it has something to do with that, but I'm not an expert myself... Do you get any php errors or a debug.log?

**Comment by tonihaupt** [comment]
Nice hint and that's what i got from my nginx-error.log:

`
PHP message: PHP Fatal error:  Uncaught Error: Undefined class constant 'NAMED_TYPE' in /Users/tonhaupt/Development/private/wp-blog/web/app/plugins/vuewp-graphql-master/Lib/webonyx/graphql-php/src/Validator/Rules/KnownTypeNames.php:22
Stack trace:
#0 [internal function]: GraphQL\Validator\Rules\KnownTypeNames->__invoke(Object(GraphQL\Validator\ValidationContext))
#1 /Users/tonhaupt/Development/private/wp-blog/web/app/plugins/vuewp-graphql-master/Lib/webonyx/graphql-php/src/Validator/DocumentValidator.php(344): call_user_func_array(Object(GraphQL\Validator\Rules\KnownTypeNames), Array)
#2 /Users/tonhaupt/Development/private/wp-blog/web/app/plugins/vuewp-graphql-master/Lib/webonyx/graphql-php/src/Validator/DocumentValidator.php(110): GraphQL\Validator\DocumentValidator::visitUsingRules(Object(GraphQL\Schema), Object(GraphQL\Language\AST\DocumentNode), Array)
#3 /Users/tonhaupt/Development/private/wp-blog/web/app/plugins/vuewp-graphql-master/Lib/webonyx/graphql-php/src/GraphQL.php(44): GraphQL\Validator\Docu" while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /graphql HTTP/1.1", upstream: "fastcgi://unix:/Users/tonhaupt/.valet/valet.sock:", host: "wp-blog.dev"
2017/04/20 10:10:19 [error] 253#0: *88 FastCGI sent in stderr: "PHP message: contentTypeIsJson true
`

**Comment by tonihaupt** [comment]
ahhhhh
maybe found a solution
did not install the plugin via composer. so i think it could not resolve the dependencies to graphql-php. give me two minutes and will test it out.

**Comment by tonihaupt** [comment]
Okay got always an error while to try installing with composer require ci/grapqhl-wp and says:
The requested package ci/graphql-wp could not be found in any version, there may be a typo in the package name.

So while working with composer i think there is no need to include the Lib folder (let composer do the depencies resolving like in the graphql-wp plugin)

Some tricks to install it via composer ?

**Comment by tonihaupt** [comment]
Solved it

**Comment by tonihaupt** [comment]
was a problem with my composer setup. first i had installed the original graphql-wp plugin and that was colliding with your setup and although loading your own vendor files from Lib. If you want i could clean it up and create a pull request
